#version: '3.9'

networks:
  loomanet:

volumes:
  looma_tmp:
    driver: local
    name: looma_tmp

services:
  loomaweb:
    # image: ghcr.io/looma/loomaweb:latest
    image: loomaweb:latest
    container_name: loomaweb
    volumes:
      - .:/usr/local/var/www/Looma:ro
      - /usr/local/var/www/content:/usr/local/var/www/content:ro
      - /usr/local/var/www/maps2018:/usr/local/var/www/maps2018:ro
      - /usr/local/var/www/ePaath:/usr/local/var/www/ePaath:ro

    ports:
      - 48080:8080
    restart: always
    tty: true
    depends_on:
      - loomadb
    networks:
      - loomanet

  loomadb:
    # image: ghcr.io/looma/loomadb:latest
    image: loomadb:latest
    container_name: loomadb
    ports:
      - 47017:27017
    restart: always
    tty: true
    networks:
      - loomanet

